// Blog content for the Channelpilot marketing site.
// Static data module (no CMS/backend) - rendered by BlogListPage / BlogPostPage.
// See MARKETING_SITE_STRATEGY.md §5–7 for the content plan behind this list.

export type BlogCategory =
  | 'Product'
  | 'AI Content Creation'
  | 'YouTube Growth & SEO'
  | 'Creator Economy'
  | 'Automation & Productivity'

export interface BlogPost {
  slug: string
  title: string
  category: BlogCategory
  excerpt: string
  date: string // ISO yyyy-mm-dd
  readMins: number
  // Paragraphs to render. A paragraph starting with "## " renders as an <h2> subheading.
  body: string[]
}

export const CATEGORIES: BlogCategory[] = [
  'Product',
  'AI Content Creation',
  'YouTube Growth & SEO',
  'Creator Economy',
  'Automation & Productivity',
]

export const BLOG_POSTS: BlogPost[] = [
  // ── Product (6) ──────────────────────────────────────────────────────────
  {
    slug: 'how-channelpilot-turns-a-topic-into-a-video',
    title: 'How Channelpilot Turns One Topic Into a Fully Produced Video',
    category: 'Product',
    excerpt: 'A walk-through of what actually happens between typing a topic and a finished video landing in your review queue.',
    date: '2026-01-08',
    readMins: 6,
    body: [
      'Type a topic. A few minutes later, a fully produced video is sitting in your review queue - script, voiceover, visuals, thumbnail, and captions all done. It looks like magic from the outside, so here is what is actually happening underneath.',
      '## Step 1: Script',
      'The topic (plus your channel\'s niche, audience, and tone settings) goes to an AI script generator that outputs a structured script: title, description, tags, and a segment-by-segment narration broken into timed beats. If you already wrote your own script, that same step just converts your text into the same structured format instead of generating one from scratch.',
      '## Step 2: Audio',
      'Each segment is sent to a text-to-speech engine using your chosen voice. Background music is optionally layered underneath at a level that never competes with narration.',
      '## Step 3: Visuals',
      'For every segment, the pipeline searches for matching stock footage or images, or generates them, based on the segment\'s content - not just the title. This is why a 10-minute video doesn\'t just loop three generic clips.',
      '## Step 4: Render',
      'Audio, visuals, music, and any custom thumbnail are assembled into a single MP4, with automatic chapter markers generated from the segment structure if enabled.',
      '## Step 5: Review, then upload',
      'Nothing publishes automatically without your review step (unless you\'ve explicitly queued it). You get a finished video, a generated thumbnail, and the option to tweak SEO metadata before it goes to YouTube - and, if configured, straight to Shorts, Reels, and TikTok as well.',
      'The whole point of showing you every one of these stages individually - not just a spinner that says "processing" - is that when something does go wrong, you know exactly which stage failed and why, instead of staring at a black box.',
    ],
  },
  {
    slug: 'inside-the-pipeline-script-voice-visuals-render-upload',
    title: 'Inside the Pipeline: Script, Voice, Visuals, Render, Upload',
    category: 'Product',
    excerpt: 'Why we designed the pipeline as five visible stages instead of one opaque "generate video" button.',
    date: '2026-01-15',
    readMins: 5,
    body: [
      'Most AI video tools show you a single progress bar and a vague status message. We deliberately broke the pipeline into five named stages - Script Generation, Audio & Voiceover, Visuals Assembly, Final Render, YouTube Upload - because each one fails differently, and a creator debugging a stuck job needs to know which one to look at.',
      '## Why granularity matters',
      'A script-generation failure usually means an API key issue. A render failure usually means a disk-space or corrupt-clip issue. An upload failure usually means an expired YouTube auth token. Collapsing all of that into "something went wrong" wastes your time; naming the stage tells you where to look immediately.',
      '## Each stage is independently retryable',
      'If visuals assembly fails because a stock-footage provider timed out, you don\'t need to regenerate the script or the voiceover - the pipeline retries from the failed stage forward, not from zero.',
      '## Real-time status, not a black box',
      'While a job runs, the dashboard shows the live step and - where the data supports it - a percentage and an ETA estimated from your own channel\'s historical job durations, not a generic guess.',
      'This transparency is a design principle, not a cosmetic choice: it is the same reasoning behind showing honest, sometimes unflattering data everywhere else in the product (see our Analytics honesty audit) - a dashboard you can\'t trust is worse than no dashboard at all.',
    ],
  },
  {
    slug: 'multi-platform-publishing-one-video-five-destinations',
    title: 'Multi-Platform Publishing: One Video, Five Destinations',
    category: 'Product',
    excerpt: 'How a single pipeline run produces YouTube, Shorts, Reels, and TikTok output without five separate exports.',
    date: '2026-01-22',
    readMins: 5,
    body: [
      'A single topic submission can end up published to YouTube (long-form), YouTube Shorts, Instagram Reels, TikTok, and Facebook Reels - without you touching an editing timeline five separate times.',
      '## Two ways to get vertical content',
      'The pipeline supports two Shorts modes: "separate," where a short is scripted and rendered independently alongside the long-form video, and "extract," where the highest-retention segment of the long-form video is automatically cut into a vertical clip. Which one is right depends on whether your Shorts are meant to stand alone or act as trailers for the long-form video.',
      '## Distribution is not an afterthought',
      'Once a video is uploaded, the same content - retitled and reformatted per platform\'s norms - is queued for Instagram Reels, TikTok, and Facebook Reels through the social distribution layer, so one submission genuinely reaches every platform your audience is on.',
      '## Why this matters more than another editing feature',
      'Editing tools solve production time. They don\'t solve distribution time - logging into four different apps, resizing, re-captioning, and re-uploading the same video by hand is where most solo creators actually lose their week. Automating distribution, not just production, is the bigger lever.',
    ],
  },
  {
    slug: 'why-we-show-every-pipeline-step',
    title: 'Why We Show You Every Pipeline Step (No Black Boxes)',
    category: 'Product',
    excerpt: 'A product philosophy post on radical transparency, and what it costs us to maintain it.',
    date: '2026-01-29',
    readMins: 4,
    body: [
      'It would be simpler, from an engineering standpoint, to hide the pipeline\'s internals behind a single "Generating your video…" spinner. We chose not to, and it has real costs - more UI surface, more states to design for, more ways for a stage to visibly fail in front of a user instead of quietly failing behind a loading screen.',
      '## The tradeoff we made on purpose',
      'We\'d rather you see "Visuals Assembly - fetching stock footage (failed, retrying)" than a generic spinner that eventually times out with no explanation. Yes, it means admitting in the UI when something is slow or broken. We think that\'s a better product than one that hides its own failure modes.',
      '## This extends to analytics, not just pipeline status',
      'The same principle drove us to fix a real bug where our own Analytics dashboard was showing "all time" labels on what was actually a rolling 30-day window, and to relabel it honestly rather than leave a flattering-but-wrong number on screen. A dashboard that lies to make itself look good isn\'t a feature.',
      'Radical transparency is slower to build and less flattering in a demo. We think it\'s the only way a creator can actually trust a tool that produces content on their behalf without their hands on every frame.',
    ],
  },
  {
    slug: 'scheduling-a-month-of-content-in-one-afternoon',
    title: 'Scheduling a Month of Content in One Afternoon',
    category: 'Product',
    excerpt: 'How the topic queue and scheduler turn batch planning into a set-and-forget workflow.',
    date: '2026-02-05',
    readMins: 5,
    body: [
      'The single highest-leverage habit we see among creators who actually hit consistent upload schedules: they don\'t plan one video at a time. They batch a month of topics in one sitting, queue them, and let the scheduler handle the rest.',
      '## How the queue works',
      'Add topics to the queue in any order - a scraped list, a brainstorm, or AI-suggested ideas. Each queued topic can be assigned a channel and, optionally, a specific publish date and time. The scheduler picks up queued topics automatically at the configured cadence, so you never have to remember to manually start the next job.',
      '## Cadence, not chaos',
      'Rather than reacting to "I should probably post something today," the queue lets you decide once - say, three long-form videos and five Shorts per week - and then simply keep the queue topped up. The scheduler enforces the cadence even when you\'re not watching.',
      '## What to actually batch',
      'Topics batch well. Fully written custom scripts batch well. What doesn\'t batch well is anything time-sensitive - trending news topics lose their edge if they sit in a queue for two weeks. Mix an evergreen queue with occasional manual "run now" jobs for anything reactive.',
    ],
  },
  {
    slug: 'from-long-form-to-shorts-automatic-clipping',
    title: 'From Long-Form to Shorts: How Automatic Clipping Works',
    category: 'Product',
    excerpt: 'The mechanics behind extracting a vertical Short from an existing long-form video.',
    date: '2026-02-12',
    readMins: 4,
    body: [
      'Every long-form video is a source of at least one good Short - the trick is finding which 30–60 seconds actually stands alone. Manually scrubbing a 10-minute video looking for a clip is one of the more tedious parts of content production, so the pipeline automates the search.',
      '## What "extract" mode looks for',
      'In extract Shorts mode, the pipeline analyzes the segment structure created during script generation - which segments contain a hook, a payoff, or a self-contained idea - and selects the strongest candidate rather than simply grabbing the first 60 seconds.',
      '## Reformatting, not just cropping',
      'A cropped 16:9 video centered into a 9:16 frame usually looks obviously repurposed. The extraction step reflows text elements and crops around the actual subject of each shot, so the output looks native to vertical platforms rather than letterboxed.',
      '## When to use "separate" instead',
      'If your long-form videos are structured as a single continuous argument rather than discrete self-contained beats, extraction has less to work with - that\'s when generating an independently scripted Short (separate mode) produces a stronger standalone piece.',
    ],
  },

  // ── AI Content Creation (6) ─────────────────────────────────────────────
  {
    slug: 'can-ai-generated-videos-compete-on-youtube-2026',
    title: 'Can AI-Generated Videos Actually Compete on YouTube in 2026?',
    category: 'AI Content Creation',
    excerpt: 'An honest look at where AI-produced content wins, and where it still visibly loses to manual production.',
    date: '2026-02-19',
    readMins: 7,
    body: [
      'The honest answer is: it depends entirely on the format, not the fact that AI was involved. Some formats - explainer content, list videos, faceless narration channels, news roundups - have always been closer to "structured information + narration" than to personality-driven storytelling, and AI production genuinely competes there.',
      '## Where AI content wins',
      'Anywhere the value is the information itself, not the presenter\'s face or improvisational charisma. Educational explainers, history narration, "top 10" formats, and niche how-to content routinely perform well when produced end-to-end by AI, because the audience is there for the payoff, not the personality.',
      '## Where it still loses',
      'Reaction content, vlogging, comedy that depends on timing and delivery, and anything built around a specific creator\'s established on-camera persona. No script generator replaces a comedian\'s timing, and pretending otherwise sets creators up for a worse video, not a better one.',
      '## The metric that actually matters: retention, not "does it look AI"',
      'YouTube doesn\'t have an "AI content" penalty in its ranking algorithm - it ranks on watch time, click-through rate, and session duration, the same as any other video. A well-produced AI video with strong retention outranks a mediocre manually-produced one, and vice versa. The question to ask isn\'t "is this AI," it\'s "does someone actually watch this to the end."',
      'Our own retention data across the videos this platform produces bears this out - some topics retain 40%+ of viewers to the end, others barely clear single digits, and the difference is almost entirely about topic-format fit, not production method.',
    ],
  },
  {
    slug: 'honest-limits-of-ai-video-generation',
    title: 'The Honest Limits of AI Video Generation (What It Still Can\'t Do)',
    category: 'AI Content Creation',
    excerpt: 'A direct list of what current AI video pipelines - including ours - genuinely cannot do yet.',
    date: '2026-02-26',
    readMins: 6,
    body: [
      'It\'s easy to oversell AI video tools. We\'d rather tell you plainly what doesn\'t work yet, because setting expectations correctly is cheaper than losing your trust after the fact.',
      '## It can\'t fake genuine on-camera presence',
      'If your niche depends on a recognizable host - a face, a voice people know, a personality with inside jokes and callbacks - AI narration is a downgrade, not an upgrade. It\'s a tool for faceless and semi-faceless formats, not a replacement for an established creator brand.',
      '## It can\'t see what YouTube itself won\'t show us',
      'Impressions and click-through rate are not exposed by any public YouTube API - full stop. Any tool claiming to show you real-time CTR data server-side is either estimating it or scraping YouTube Studio in a way that risks your account. We\'d rather be honest that this data gap exists than fake a number.',
      '## It can\'t guarantee virality',
      'No script generator, however good, can guarantee a video takes off - retention, topic timing, and algorithmic distribution are still probabilistic. What automation buys you is more attempts per week at the same quality bar, which compounds, but it does not buy you a guaranteed hit.',
      '## It still needs a human decision-maker',
      'Every pipeline run has a review step for a reason. AI script quality is good, not infallible - factual claims in generated scripts should be spot-checked, especially in news, health, or finance niches where being wrong has real consequences.',
    ],
  },
  {
    slug: 'ai-prompts-that-dont-sound-like-ai',
    title: 'How to Write AI Prompts That Don\'t Sound Like AI',
    category: 'AI Content Creation',
    excerpt: 'Concrete prompt-writing habits that measurably change how "AI" a generated script sounds.',
    date: '2026-03-05',
    readMins: 5,
    body: [
      'Generic prompts produce generic scripts - the flattened, over-hedged, list-of-facts tone people mean when they say something "sounds like AI." Specific prompts produce specific scripts. The difference is almost entirely in what you give the model to work with.',
      '## Give it a point of view, not just a topic',
      'A prompt like "make a video about the history of trains" produces a Wikipedia summary read aloud. A prompt like "argue that the decline of passenger rail in the US was a political choice, not an economic inevitability" produces a script with an actual argument to follow.',
      '## Specify the audience\'s existing knowledge',
      'Telling the generator your audience already knows the basics changes the script from a beginner explainer into something with real depth - and cuts the throat-clearing intro that AI scripts default to when they assume zero prior knowledge.',
      '## Ask for a hook, explicitly',
      'Scripts that open with a direct claim or a specific number retain viewers dramatically better than ones that open with "In this video, we\'re going to talk about…" - if your prompt doesn\'t ask for a hook, most generators default to the safe, generic opener.',
      '## Give it a tone reference, not just an adjective',
      '"Conversational" means something different to every model. "Write like you\'re explaining this to a smart friend who disagrees with you" is a more specific, more reliably followed instruction than "conversational tone."',
    ],
  },
  {
    slug: 'faceless-youtube-channels-realistic-playbook',
    title: 'Faceless YouTube Channels: A Realistic Playbook',
    category: 'AI Content Creation',
    excerpt: 'What actually works for faceless channels in 2026, stripped of the "get rich quick" framing.',
    date: '2026-03-12',
    readMins: 6,
    body: [
      'Faceless channels get sold as a shortcut. They\'re not - they\'re a different production model with a different cost structure, and they work best in specific formats, not universally.',
      '## Formats that actually work faceless',
      'History and explainer narration, curated compilation content, data-driven "here\'s what the numbers actually show" videos, and niche educational content all work without a host, because the value is the information and the pacing, not a face.',
      '## Formats that don\'t',
      'Anything that depends on spontaneous reaction, comedic timing, or an audience relationship with a specific person struggles without a face - faceless comedy and faceless vlogging are much harder to make work than faceless education.',
      '## The real bottleneck is consistency, not concept',
      'Most faceless channels don\'t fail because the concept was bad - they fail because the creator burns out on production after a few weeks and the upload cadence collapses. This is precisely the problem automation is built to solve: a queue of topics and a scheduler that keeps publishing even during a busy week.',
      '## Realistic timeline expectations',
      'YouTube Partner Program eligibility requires real lifetime watch-hour and subscriber thresholds (4,000 hours / 1,000 subscribers) - there is no faceless shortcut around that math. Plan for months of consistent output before monetization, not weeks.',
    ],
  },
  {
    slug: 'ai-voiceovers-vs-human-narration',
    title: 'AI Voiceovers vs. Human Narration: A Side-by-Side Breakdown',
    category: 'AI Content Creation',
    excerpt: 'Where synthetic voices are indistinguishable from human narration, and where the gap is still audible.',
    date: '2026-03-19',
    readMins: 5,
    body: [
      'Modern text-to-speech has closed most of the gap with human narration for straightforward informational content - but "most" isn\'t "all," and knowing where the remaining gap is helps you pick the right voice for the right script.',
      '## Where AI voices are genuinely indistinguishable',
      'Steady-pace explainer narration, list-format videos, and news-style delivery are where synthetic voices are hardest to tell apart from a human narrator, because the delivery is naturally even and doesn\'t depend on emotional range.',
      '## Where the gap is still audible',
      'Comedic timing, sarcasm, and rapid emotional shifts within a single sentence are still the hardest thing for synthetic voices to nail - a joke that depends on a half-second pause before the punchline often lands flat with AI narration.',
      '## Picking a voice for your niche',
      'Match the voice\'s natural pacing to your content\'s pacing, not just its gender or accent. A voice tuned for calm explainer content will underperform on high-energy list videos, and vice versa - most platforms offering 20+ voices exist precisely so you can match tone to format, not just personal preference.',
      '## The practical test',
      'Play a generated clip to someone unfamiliar with the video without telling them it\'s AI. If they don\'t ask, the voice is doing its job for that content type. If they immediately ask "is this AI," that\'s useful signal to try a different voice or format before publishing.',
    ],
  },
  {
    slug: 'multilingual-content-what-ai-translation-still-gets-wrong',
    title: 'Multilingual Content: Reaching Audiences AI Translation Still Gets Wrong',
    category: 'AI Content Creation',
    excerpt: 'Why native-language script generation outperforms translate-after-the-fact for non-English audiences.',
    date: '2026-03-26',
    readMins: 5,
    body: [
      'Translating an English script into another language after the fact is the fastest way to produce multilingual content - and usually the weakest. Idioms don\'t translate, jokes don\'t translate, and pacing that worked in English often reads stiffly once mechanically translated.',
      '## Generate natively, don\'t translate after the fact',
      'Generating the script directly in the target language - with the AI reasoning in that language from the start, not translating a finished English script - produces noticeably more natural phrasing, because idioms and structure are chosen for the target language rather than carried over from English.',
      '## Voice matching matters as much as language',
      'A native-language script paired with an accented or awkward-sounding voice for that language undoes the benefit. Matching both the script generation language and the voiceover language to the actual target audience is what makes multilingual content feel native rather than dubbed.',
      '## Where this pays off fastest',
      'Spanish, Portuguese, Hindi, and Arabic audiences are consistently underserved by the volume of native-language content relative to their audience size on YouTube - meaning less competition for well-produced native-language videos in those languages compared to an oversaturated English-language niche.',
    ],
  },

  // ── YouTube Growth & SEO (6) ────────────────────────────────────────────
  {
    slug: 'youtube-seo-2026-what-actually-moves-the-needle',
    title: 'YouTube SEO in 2026: What Actually Moves the Needle',
    category: 'YouTube Growth & SEO',
    excerpt: 'A grounded look at which SEO levers still matter, and which ones are folklore at this point.',
    date: '2026-04-02',
    readMins: 6,
    body: [
      'YouTube SEO advice hasn\'t updated much since 2018 in most corners of the internet, even though the ranking system has. Here\'s what actually still moves the needle, based on real checklist auditing across hundreds of videos.',
      '## Still matters: title clarity and length',
      'Titles over roughly 70 characters get truncated in search and suggested-video surfaces, cutting off the exact keyword or hook that was supposed to earn the click. Front-loading the specific, searchable part of the title in the first 60 characters is a small, mechanical fix with an outsized effect.',
      '## Still matters: chapters in the description',
      'Auto-generated or manual chapter markers do two things at once - they improve navigation (helping retention on longer videos) and they give YouTube\'s indexing system explicit topic segments to associate with search queries.',
      '## Mostly folklore: keyword stuffing in tags',
      'Tags carry a fraction of the SEO weight they did years ago. Title and the first two sentences of the description do far more work for discoverability than a long tag list ever will.',
      '## Doesn\'t exist: guaranteed impressions/CTR manipulation tricks',
      'Impressions and click-through rate aren\'t exposed by any public API, and no legitimate tool can directly manipulate the impression algorithm from outside YouTube Studio. Be skeptical of any tool claiming otherwise - the honest lever here is making a better thumbnail and title, not gaming a black box.',
    ],
  },
  {
    slug: 'titles-thumbnails-first-15-seconds',
    title: 'Titles, Thumbnails, and the First 15 Seconds: Where Retention Is Won or Lost',
    category: 'YouTube Growth & SEO',
    excerpt: 'The three decision points that determine whether a video gets watched at all, and to the end.',
    date: '2026-04-09',
    readMins: 5,
    body: [
      'Three moments decide most of a video\'s fate: the title/thumbnail combination (does it get clicked), the first 15 seconds (does the click get honored), and the mid-video pacing (does the viewer stay to the end). Most creators over-invest in production quality and under-invest in these three specifically.',
      '## The click decision happens in under a second',
      'A thumbnail and title are evaluated together, almost instantly, against everything else on the same results page. A technically accurate but bland title loses to a slightly oversold but specific one - specificity, not cleverness, is what earns the click.',
      '## The first 15 seconds have to pay off the title\'s promise immediately',
      'Viewers who click based on a title\'s promise and then sit through 30 seconds of channel intro before the payoff starts will disproportionately leave. Real average-view-percentage data across produced videos shows a sharp early drop-off exactly where the payoff is delayed.',
      '## Mid-video pacing is the quiet retention killer',
      'A video that opens strong but slows into a flat, unvarying pace in the middle loses viewers steadily rather than in one dramatic drop - this is why segment-level pacing (via chapters and varied visual pacing per segment) matters more than people assume.',
    ],
  },
  {
    slug: 'how-the-youtube-partner-program-math-works',
    title: 'How the YouTube Partner Program Math Actually Works',
    category: 'YouTube Growth & SEO',
    excerpt: 'The real lifetime thresholds behind monetization eligibility, and the mistake most trackers make.',
    date: '2026-04-16',
    readMins: 5,
    body: [
      'YPP eligibility requires 4,000 lifetime watch hours and 1,000 subscribers within a rolling 365-day window (or the Shorts-specific equivalent). The most common mistake in tracking this progress isn\'t misunderstanding the thresholds - it\'s comparing a rolling 30-day snapshot against a lifetime threshold and badly understating real progress.',
      '## The 30-day trap',
      'If your dashboard shows "watch hours: 143" but the number quietly refreshes to a small rolling window every month, you can spend months thinking you\'re barely progressing toward YPP when your real lifetime total is far higher. This exact bug - a rolling snapshot compared against a lifetime goal - is worth checking for in any analytics tool you use.',
      '## What actually accelerates the timeline',
      'Watch hours accumulate faster from longer-form content with strong retention than from a high volume of very short videos, purely because of the arithmetic - ten minutes of watch time from one video is easier to earn than the same total spread across dozens of short clips with lower absolute watch time each.',
      '## Subscribers vs. watch hours: which gates you first',
      'For most channels producing longer-form content, watch hours are the binding constraint, not subscribers - a channel can cross 1,000 subscribers well before 4,000 lifetime watch hours if videos are short, so track both numbers, not just the more visible subscriber count.',
    ],
  },
  {
    slug: 'best-times-to-publish-backed-by-real-data',
    title: 'Best Times to Publish, Backed by Real Channel Data',
    category: 'YouTube Growth & SEO',
    excerpt: 'Why generic "best time to post" advice is usually wrong for your specific channel.',
    date: '2026-04-23',
    readMins: 5,
    body: [
      'Generic "post at 3pm on Thursdays" advice is aggregated across millions of unrelated channels and audiences - it is almost never the right answer for your specific channel\'s specific audience.',
      '## Why raw view counts mislead this analysis',
      'Ranking publish times by raw view count unfairly favors older videos, which have simply had more time to accumulate views. A defensible ranking measures views-per-day-since-publish instead, so a video published two weeks ago competes fairly against one published eight months ago.',
      '## Low-sample honesty matters here too',
      'A channel with 37 analyzed videos publishing across 20 different day/time combinations has very few data points per slot - a ranking system should flag low-confidence results honestly instead of asserting "Tuesday 6pm is best" off two data points.',
      '## What to actually do with this data',
      'Use it to pick a consistent publish window, not to chase a "perfect" slot that shifts every time you re-run the analysis. Consistency in publish timing helps subscriber habit-forming more than optimizing the exact hour.',
    ],
  },
  {
    slug: 'traffic-sources-explained',
    title: 'Traffic Sources Explained: Why Most of Your Views Aren\'t From Search',
    category: 'YouTube Growth & SEO',
    excerpt: 'A breakdown of where views actually come from, and why that changes what you should optimize.',
    date: '2026-04-30',
    readMins: 5,
    body: [
      'Most new creators assume search is the dominant traffic source. In practice, across a wide range of channels, Shorts feed placement, suggested/related videos, and browse features usually account for a larger share of views than direct search.',
      '## What the breakdown usually looks like',
      'A typical mix skews heavily toward Shorts and suggested placement, with search, external links, hashtags, and playlists making up smaller shares - the exact ratio varies by niche, but search rarely dominates the way most creators expect.',
      '## Why this changes what you optimize for',
      'If Shorts and suggested placement drive most views, thumbnail/title SEO keyword-stuffing is optimizing for a smaller slice of your actual traffic than it feels like. Retention and completion rate - which feed the suggested/Shorts algorithms - deserve more of your attention than search-keyword tuning alone.',
      '## A data honesty note',
      'YouTube\'s Analytics API does not support combining a video-level dimension with traffic-source-type in a single bulk query - so any tool claiming instant per-video traffic-source breakdowns across your whole channel in one call is either estimating or making one API call per video (expensive) behind the scenes. Channel-wide, on-demand breakdowns are the honest middle ground.',
    ],
  },
  {
    slug: 'chapters-pinned-comments-cards-small-features-real-gains',
    title: 'Chapters, Pinned Comments, and Cards: Small Features, Real Watch-Time Gains',
    category: 'YouTube Growth & SEO',
    excerpt: 'The unglamorous checklist items that consistently move retention and engagement metrics.',
    date: '2026-05-07',
    readMins: 4,
    body: [
      'None of these are exciting. All of them measurably help. A quick audit checklist worth running on every video before it goes live.',
      '## Chapters',
      'Auto-generated from your script\'s segment structure, chapters give viewers a map of the video and let them jump to the part they care about - which keeps them on the video instead of abandoning it entirely when the intro runs long.',
      '## Pinned first comment',
      'A pinned comment pointing to your next video or asking a direct question is one of the few engagement levers fully within your control at publish time - it costs nothing and consistently nudges comment activity, which correlates with session-duration signals.',
      '## End-screen and card discipline',
      'Directing viewers to a specific next video (ideally your best-performing related content, not just your most recent upload) keeps a session going instead of ending it - cross-linking to a genuinely relevant next video matters more than linking to whatever published most recently.',
      '## Title length as a checklist item',
      'A title over roughly 70 characters gets truncated in several YouTube surfaces - checking this mechanically, on every single upload, catches an easy miss that otherwise silently costs clicks.',
    ],
  },

  // ── Creator Economy (6) ─────────────────────────────────────────────────
  {
    slug: 'real-economics-of-running-a-youtube-channel-as-a-business',
    title: 'The Real Economics of Running a YouTube Channel as a Business',
    category: 'Creator Economy',
    excerpt: 'A frank look at the cost structure behind consistent content production, beyond ad revenue.',
    date: '2026-05-14',
    readMins: 6,
    body: [
      'Ad revenue is the visible number, but it\'s rarely the whole economic story for a channel run as an actual business. The real cost structure includes production time (or its automation-equivalent cost), API/tooling spend, and the opportunity cost of everything else you didn\'t do with those hours.',
      '## Production cost per video is the number that matters',
      'Whether measured in hours of manual editing or in AI/API cost per rendered video, the relevant unit economic question is: what does one video cost to produce, and does its expected revenue (ad revenue + sponsorships + off-platform monetization) exceed that cost with margin to spare?',
      '## Where automation changes the math',
      'When production cost per video drops from hours of manual work to a few dollars of API cost, the breakeven bar for "is this topic worth making a video about" drops dramatically - topics that wouldn\'t have justified a full manual production cycle become worth testing.',
      '## Diversify revenue, not just content',
      'Ad revenue alone is a volatile, CPM-dependent income stream. Sponsorships, affiliate links, and off-platform products (courses, tools, communities) built on top of an audience are what make a channel resemble an actual business rather than a payout at YouTube\'s mercy.',
      '## The real risk isn\'t the algorithm, it\'s inconsistency',
      'Channels that stop publishing for months lose momentum that\'s expensive to rebuild - the algorithm doesn\'t punish inconsistency directly, but audience habit and session-based discovery both reward channels that keep showing up.',
    ],
  },
  {
    slug: 'multi-channel-networks-without-the-overhead',
    title: 'Multi-Channel Networks Without the Overhead: A Solo Creator\'s Guide',
    category: 'Creator Economy',
    excerpt: 'How solo operators run multiple channels without multiplying their workload proportionally.',
    date: '2026-05-21',
    readMins: 5,
    body: [
      'Running five channels used to mean five times the editing workload. It doesn\'t have to anymore - the constraint that used to force "one creator, one channel" was production time, and that constraint has genuinely loosened.',
      '## What actually scales across channels',
      'A shared pipeline with per-channel profiles (niche, tone, voice, visual style, language) lets one operator manage several distinct channel identities without maintaining five separate production workflows from scratch.',
      '## What doesn\'t scale: attention and quality control',
      'Automation removes the production bottleneck, not the judgment bottleneck. Someone still has to review scripts for accuracy, pick genuinely good topics, and catch a channel drifting off-brand - spreading that oversight across too many channels at once degrades quality faster than it multiplies revenue.',
      '## A realistic starting number',
      'Most solo operators find 2–4 channels is the point where oversight is still manageable without becoming a full-time management job in itself - beyond that, either quality per channel drops or it\'s time to bring on a second person.',
    ],
  },
  {
    slug: 'diversifying-beyond-youtube-one-strategy',
    title: 'Diversifying Beyond YouTube: Shorts, Reels, and TikTok as One Strategy',
    category: 'Creator Economy',
    excerpt: 'Treating multi-platform distribution as a single strategy instead of separate side projects.',
    date: '2026-05-28',
    readMins: 5,
    body: [
      'Most creators treat "also post on TikTok" as an afterthought bolted onto their real channel, YouTube. That framing wastes most of the platform diversification opportunity - the point isn\'t a side project, it\'s a single content strategy expressed across formats.',
      '## One idea, several formats, not several ideas',
      'A long-form video\'s strongest 45 seconds is your Shorts/Reels/TikTok content - not a separate brainstorm. Planning content this way from the start (rather than editing clips out of a finished long-form video as an afterthought) produces stronger standalone short-form pieces.',
      '## Platform-specific norms still matter',
      'Captions, pacing, and hook style differ enough between TikTok and Instagram Reels that a direct re-upload underperforms a lightly platform-adapted version - small adjustments to captions and opening frame per platform are worth the marginal effort.',
      '## Why this reduces platform risk, not just adds reach',
      'A channel entirely dependent on one platform\'s algorithm changes is fragile. Genuine multi-platform presence - not just a mirrored upload, but an actual audience on each - is the real hedge against any single platform\'s policy or algorithm shift.',
    ],
  },
  {
    slug: 'how-much-to-reinvest-into-content-production',
    title: 'How Much Should You Reinvest Into Content Production?',
    category: 'Creator Economy',
    excerpt: 'A framework for deciding how aggressively to reinvest revenue into scaling output.',
    date: '2026-06-04',
    readMins: 5,
    body: [
      'The instinct once revenue starts is to reinvest everything into scaling faster. That\'s often right, but not always - the framework worth using is marginal cost per video versus marginal expected revenue per video, not "reinvest as much as possible."',
      '## When aggressive reinvestment makes sense',
      'If your cost per video is low relative to expected revenue, and your bottleneck is genuinely topic/output volume rather than quality or audience saturation, scaling output aggressively compounds quickly.',
      '## When it doesn\'t',
      'If a niche has a limited addressable audience, producing more videos per week doesn\'t proportionally grow views - it just spreads the same audience thinner across more content, and quality per video may drop as a side effect of speed.',
      '## A simple test before scaling up',
      'Look at whether your last several videos are still growing view counts over time, or plateauing. Plateauing output in a saturated format is a signal to diversify topics or formats before adding more volume, not a signal to just publish more of the same.',
    ],
  },
  {
    slug: 'burnout-is-the-number-one-reason-creators-quit',
    title: 'Burnout Is the #1 Reason Creators Quit - Here\'s the Data',
    category: 'Creator Economy',
    excerpt: 'Why sustainable cadence beats short-term intensity, and what actually causes creator burnout.',
    date: '2026-06-11',
    readMins: 5,
    body: [
      'Ask any creator who quit why, and the honest answer is rarely "the algorithm killed my channel." It\'s far more often exhaustion from a production cadence that was never sustainable in the first place.',
      '## The pattern that leads to burnout',
      'A strong initial cadence (daily uploads, aggressive experimentation) followed by a collapse to zero is a far more common failure mode than a slow, steady decline. Creators who start unsustainably fast tend to stop entirely, rather than settling into a slower but permanent cadence.',
      '## What sustainable cadence actually looks like',
      'A cadence you can maintain during a bad week - sick, busy, unmotivated - is the only cadence that survives long enough to compound. This is precisely the argument for batching and automation: not to produce more in absolute terms, but to make the same modest cadence require far less weekly willpower to sustain.',
      '## The role of a queue in preventing burnout specifically',
      'A pre-filled topic queue and scheduler mean a bad week doesn\'t break your publishing streak - the system keeps a baseline cadence going even when you personally have zero bandwidth that week, which is exactly when burnout-driven quitting happens.',
    ],
  },
  {
    slug: 'building-a-content-business-that-survives-algorithm-changes',
    title: 'Building a Content Business That Survives an Algorithm Change',
    category: 'Creator Economy',
    excerpt: 'What actually insulates a channel from sudden algorithm shifts, and what doesn\'t.',
    date: '2026-06-18',
    readMins: 5,
    body: [
      'Every few months, a visible algorithm shift tanks some channels and lifts others overnight, and the creators who survive it aren\'t the ones who guessed the change correctly in advance - they\'re the ones whose business didn\'t depend entirely on one platform\'s current ranking behavior.',
      '## Owned audience beats rented audience',
      'An email list, a Discord community, or any audience relationship that exists independently of a single platform\'s feed is the actual insulation against algorithm volatility - subscribers on a platform are a rented relationship the platform can change the terms of at any time.',
      '## Format diversity beats platform diversity alone',
      'Being on five platforms with the exact same content format is less resilient than having genuinely different formats (long-form, Shorts, community posts) that respond differently to the same algorithm shift.',
      '## Revenue diversity is the final layer',
      'Ad revenue tied to one platform\'s CPM and policy decisions is the most exposed income stream a creator has. Sponsorships and off-platform products, built on the audience but not gated by any single platform\'s payout terms, are what actually make a content business durable through an algorithm change.',
    ],
  },

  // ── Automation & Productivity (6) ───────────────────────────────────────
  {
    slug: 'the-case-for-automating-the-boring-80-percent',
    title: 'The Case for Automating the Boring 80% of Content Production',
    category: 'Automation & Productivity',
    excerpt: 'A breakdown of which parts of video production are genuinely worth automating, and which aren\'t.',
    date: '2026-06-25',
    readMins: 5,
    body: [
      'Not every part of content production is equally worth a creator\'s personal attention. Roughly 80% of the work - transcription-adjacent script structuring, voiceover recording, stock footage sourcing, thumbnail formatting, upload metadata entry - is mechanical and repeatable. The other 20% - topic selection, factual review, brand voice, creative direction - genuinely benefits from a human in the loop.',
      '## Automate the mechanical, keep the judgment',
      'The goal isn\'t "remove the human from content production." It\'s removing the human from the parts where a human adds no distinguishing value over a well-tuned automated process, so their attention is spent entirely on the 20% that actually differentiates the channel.',
      '## The compounding effect of small time savings',
      'Saving 30 minutes per video on metadata entry and upload logistics sounds trivial per-video - across 20 videos a month, it\'s 10 hours back, which is enough time to actually plan next month\'s topics properly instead of always producing reactively.',
      '## Where automation should stop',
      'Automating topic selection entirely, with zero human review, is where quality control tends to break down - a queue that runs unattended for months without anyone spot-checking output drifts, the same way any unmonitored system does.',
    ],
  },
  {
    slug: 'batch-production-weekly-beats-daily-grinding',
    title: 'Batch Production: Why Weekly Uploads Beat Daily Grinding',
    category: 'Automation & Productivity',
    excerpt: 'The case for batching content in scheduled sessions instead of daily ad-hoc production.',
    date: '2026-07-02',
    readMins: 4,
    body: [
      'Daily uploads sound more aggressive than weekly ones, but daily-grind schedules are also where most burnout-driven channel abandonment starts. Batch production - planning and queuing a week or month of content in one sitting - is usually the more durable strategy.',
      '## Why batching works better cognitively',
      'Context-switching between "come up with a topic" and "produce today\'s video" every single day is mentally expensive. Doing all the topic ideation in one focused session, then letting a queue and scheduler handle daily execution, removes that daily decision fatigue entirely.',
      '## Quality tends to improve, not just consistency',
      'Topics chosen under daily deadline pressure are often weaker than ones chosen during a calmer batch-planning session with room to actually compare ideas against each other before committing.',
      '## The scheduler is what makes batching actually work',
      'Batching a month of topics without an automated way to release them on a cadence just becomes a large backlog someone has to manually publish from - a scheduler that respects your chosen cadence is the piece that turns a batch into a genuinely hands-off pipeline.',
    ],
  },
  {
    slug: 'queue-based-workflows-planning-a-month-publishing-automatically',
    title: 'Queue-Based Workflows: Planning a Month, Publishing Automatically',
    category: 'Automation & Productivity',
    excerpt: 'A practical guide to structuring a topic queue that keeps publishing steady without daily attention.',
    date: '2026-07-09',
    readMins: 5,
    body: [
      'A queue is only as useful as how it\'s structured. A flat, unordered list of topics is better than nothing, but a queue organized with intent - cadence, channel assignment, and priority - is what actually produces steady, hands-off publishing.',
      '## Structure the queue around a target cadence',
      'Decide your target cadence first (e.g., 3 long-form + 2 Shorts per week) and fill the queue to match it, rather than adding topics ad-hoc and hoping the total roughly works out.',
      '## Mix evergreen and time-sensitive intentionally',
      'Evergreen topics tolerate sitting in a queue for weeks without losing relevance. Time-sensitive or trend-driven topics don\'t - keep those out of the long-running queue and run them manually, closer to real-time, so they don\'t go stale waiting their turn.',
      '## Review the queue periodically, don\'t "set and forget" forever',
      'A queue that runs for months without anyone reviewing upcoming topics can drift - a periodic (weekly or biweekly) review of what\'s queued next catches topics that no longer make sense before they publish automatically.',
    ],
  },
  {
    slug: 'what-to-automate-first-as-a-one-person-media-company',
    title: 'What to Automate First When You\'re a One-Person Media Company',
    category: 'Automation & Productivity',
    excerpt: 'A prioritized order for automating a solo content operation, based on where time actually goes.',
    date: '2026-07-16',
    readMins: 5,
    body: [
      'Solo creators often automate in the wrong order - investing in fancy analytics dashboards before fixing the parts of production that are actually eating their week. A more useful order, roughly by time saved per hour invested:',
      '## 1. Script structuring and voiceover',
      'These are the most mechanically repeatable, highest-time-cost stages for most creators - automating them first frees the most hours for the least loss of creative control, since the topic and review decisions still stay with you.',
      '## 2. Visual sourcing',
      'Manually searching and downloading stock footage per segment is tedious, low-judgment work - a strong candidate for automation immediately after script/voice, since matching visuals to segment content is a mechanical search problem, not a creative one.',
      '## 3. Multi-platform distribution',
      'Once production is automated, re-uploading the same finished video to four platforms by hand becomes the new bottleneck - automating distribution next closes that gap.',
      '## 4. Analytics and scheduling last',
      'These are valuable but not blocking - a creator can survive without automated analytics for a while. They\'re worth automating once the actual production and distribution bottlenecks are solved, not before.',
    ],
  },
  {
    slug: 'analytics-you-should-actually-check-weekly',
    title: 'Analytics You Should Actually Check Weekly (and What to Ignore)',
    category: 'Automation & Productivity',
    excerpt: 'A short, honest list of the metrics worth a weekly look, and the vanity metrics worth ignoring.',
    date: '2026-07-23',
    readMins: 4,
    body: [
      'Most analytics dashboards show 20+ numbers. Checking all of them weekly is its own form of unproductive busywork. A shorter, higher-signal list is worth actually building a habit around.',
      '## Check weekly: retention (average view percentage)',
      'This single number tells you more about whether a topic/format is working than view count alone - a video with modest views but strong retention is a format worth repeating; high views with poor retention often means a misleading thumbnail/title, not a real win.',
      '## Check weekly: traffic source mix',
      'A sudden shift in traffic source (say, a drop in Shorts-feed placement) is an early signal worth noticing before it shows up as a bigger view-count decline the following month.',
      '## Check monthly, not weekly: subscriber count and lifetime watch hours',
      'These move slowly and checking them daily or weekly mostly just produces anxiety without actionable signal - monthly is frequent enough to catch a real trend without over-indexing on daily noise.',
      '## Mostly ignore: like/dislike ratio in isolation',
      'It correlates weakly with anything actionable on its own - retention and traffic source tell you far more about what to change than engagement-ratio metrics do.',
    ],
  },
  {
    slug: 'repeatable-system-vs-chasing-every-trend',
    title: 'Building a Repeatable System vs. Chasing Every New Trend',
    category: 'Automation & Productivity',
    excerpt: 'Why a boring, repeatable production system usually outperforms constantly chasing the latest trend.',
    date: '2026-07-30',
    readMins: 5,
    body: [
      'Every few weeks there\'s a new format, trend, or tool everyone insists you need to adopt immediately. Chasing each one has a real cost: it breaks whatever repeatable system you\'d built, and most trends are gone before a slow-moving production process can even catch up.',
      '## What a repeatable system actually buys you',
      'A known, tested pipeline - script format, voice, visual style, publish cadence - that reliably produces acceptable-quality output every time is worth more than an occasional trend-chasing hit, because it compounds predictably instead of spiking and collapsing.',
      '## When it\'s actually worth breaking the system',
      'Not every trend is noise - a genuine format shift (like the rise of Shorts itself) is worth adapting a system for permanently, not just for one video. The test: is this a structural shift in how the platform surfaces content, or a two-week meme? Only the former justifies rebuilding your system.',
      '## The real skill is knowing which is which',
      'Most trend-chasing advice implicitly assumes every trend is the former. In practice, most are the latter, and the creators who build the most durable channels are usually the ones who ignore the majority of them and keep executing their repeatable system consistently.',
    ],
  },
]

export function getPostBySlug(slug: string): BlogPost | undefined {
  return BLOG_POSTS.find((p) => p.slug === slug)
}

export function getRelatedPosts(current: BlogPost, count = 3): BlogPost[] {
  return BLOG_POSTS
    .filter((p) => p.slug !== current.slug && p.category === current.category)
    .slice(0, count)
}
